# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\x12\x06\x62roker\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x10SubscribeRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"M\n\x05\x45vent\x12\x14\n\x0cwork_context\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\"0\n\x0bWorkContext\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"K\n\nWorkParams\x12\x14\n\x0cwork_context\x18\x01 \x01(\t\x12\x13\n\x0bparams_json\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"]\n\tWorkState\x12\x14\n\x0cwork_context\x18\x01 \x01(\t\x12\x12\n\nstate_name\x18\x02 \x01(\t\x12\x12\n\nstate_json\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\"~\n\x0bProgressBar\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0cwork_context\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x0b\n\x03min\x18\x05 \x01(\x01\x12\x0b\n\x03max\x18\x06 \x01(\x01\x12\x0e\n\x06is_int\x18\x07 \x01(\x08\x32\xdd\x03\n\x06\x42roker\x12\x35\n\nPushEvents\x12\r.broker.Event\x1a\x16.google.protobuf.Empty(\x01\x12\x36\n\tSubscribe\x12\x18.broker.SubscribeRequest\x1a\r.broker.Event0\x01\x12<\n\x0eRegisterParams\x12\x12.broker.WorkParams\x1a\x16.google.protobuf.Empty\x12\x34\n\tGetParams\x12\x13.broker.WorkContext\x1a\x12.broker.WorkParams\x12\x35\n\x08SetState\x12\x11.broker.WorkState\x1a\x16.google.protobuf.Empty\x12\x30\n\x08GetState\x12\x11.broker.WorkState\x1a\x11.broker.WorkState\x12=\n\x0eSetProgressBar\x12\x13.broker.ProgressBar\x1a\x16.google.protobuf.Empty\x12H\n\x15SubscribeProgressBars\x12\x18.broker.SubscribeRequest\x1a\x13.broker.ProgressBar0\x01\x42\x0cZ\n./brokerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./brokerpb'
  _globals['_SUBSCRIBEREQUEST']._serialized_start=53
  _globals['_SUBSCRIBEREQUEST']._serialized_end=91
  _globals['_EVENT']._serialized_start=93
  _globals['_EVENT']._serialized_end=170
  _globals['_WORKCONTEXT']._serialized_start=172
  _globals['_WORKCONTEXT']._serialized_end=220
  _globals['_WORKPARAMS']._serialized_start=222
  _globals['_WORKPARAMS']._serialized_end=297
  _globals['_WORKSTATE']._serialized_start=299
  _globals['_WORKSTATE']._serialized_end=392
  _globals['_PROGRESSBAR']._serialized_start=394
  _globals['_PROGRESSBAR']._serialized_end=520
  _globals['_BROKER']._serialized_start=523
  _globals['_BROKER']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
