// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/broker.proto

package brokerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkContext   string                 `protobuf:"bytes,1,opt,name=work_context,json=workContext,proto3" json:"work_context,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetWorkContext() string {
	if x != nil {
		return x.WorkContext
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WorkContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkContext) Reset() {
	*x = WorkContext{}
	mi := &file_proto_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkContext) ProtoMessage() {}

func (x *WorkContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkContext.ProtoReflect.Descriptor instead.
func (*WorkContext) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkContext) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WorkContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WorkParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkContext   string                 `protobuf:"bytes,1,opt,name=work_context,json=workContext,proto3" json:"work_context,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkParams) Reset() {
	*x = WorkParams{}
	mi := &file_proto_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkParams) ProtoMessage() {}

func (x *WorkParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkParams.ProtoReflect.Descriptor instead.
func (*WorkParams) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{3}
}

func (x *WorkParams) GetWorkContext() string {
	if x != nil {
		return x.WorkContext
	}
	return ""
}

func (x *WorkParams) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *WorkParams) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WorkState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkContext   string                 `protobuf:"bytes,1,opt,name=work_context,json=workContext,proto3" json:"work_context,omitempty"`
	StateName     string                 `protobuf:"bytes,2,opt,name=state_name,json=stateName,proto3" json:"state_name,omitempty"`
	StateJson     string                 `protobuf:"bytes,3,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkState) Reset() {
	*x = WorkState{}
	mi := &file_proto_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkState) ProtoMessage() {}

func (x *WorkState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkState.ProtoReflect.Descriptor instead.
func (*WorkState) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkState) GetWorkContext() string {
	if x != nil {
		return x.WorkContext
	}
	return ""
}

func (x *WorkState) GetStateName() string {
	if x != nil {
		return x.StateName
	}
	return ""
}

func (x *WorkState) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

func (x *WorkState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ProgressBar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkContext   string                 `protobuf:"bytes,2,opt,name=work_context,json=workContext,proto3" json:"work_context,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Min           float64                `protobuf:"fixed64,5,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,6,opt,name=max,proto3" json:"max,omitempty"`
	IsInt         bool                   `protobuf:"varint,7,opt,name=is_int,json=isInt,proto3" json:"is_int,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressBar) Reset() {
	*x = ProgressBar{}
	mi := &file_proto_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressBar) ProtoMessage() {}

func (x *ProgressBar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressBar.ProtoReflect.Descriptor instead.
func (*ProgressBar) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressBar) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProgressBar) GetWorkContext() string {
	if x != nil {
		return x.WorkContext
	}
	return ""
}

func (x *ProgressBar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgressBar) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ProgressBar) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ProgressBar) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ProgressBar) GetIsInt() bool {
	if x != nil {
		return x.IsInt
	}
	return false
}

var File_proto_broker_proto protoreflect.FileDescriptor

const file_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/broker.proto\x12\x06broker\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"q\n" +
	"\x05Event\x12!\n" +
	"\fwork_context\x18\x01 \x01(\tR\vworkContext\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"B\n" +
	"\vWorkContext\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"o\n" +
	"\n" +
	"WorkParams\x12!\n" +
	"\fwork_context\x18\x01 \x01(\tR\vworkContext\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x8b\x01\n" +
	"\tWorkState\x12!\n" +
	"\fwork_context\x18\x01 \x01(\tR\vworkContext\x12\x1d\n" +
	"\n" +
	"state_name\x18\x02 \x01(\tR\tstateName\x12\x1d\n" +
	"\n" +
	"state_json\x18\x03 \x01(\tR\tstateJson\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\xb4\x01\n" +
	"\vProgressBar\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fwork_context\x18\x02 \x01(\tR\vworkContext\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x06 \x01(\x01R\x03max\x12\x15\n" +
	"\x06is_int\x18\a \x01(\bR\x05isInt2\xdd\x03\n" +
	"\x06Broker\x125\n" +
	"\n" +
	"PushEvents\x12\r.broker.Event\x1a\x16.google.protobuf.Empty(\x01\x126\n" +
	"\tSubscribe\x12\x18.broker.SubscribeRequest\x1a\r.broker.Event0\x01\x12<\n" +
	"\x0eRegisterParams\x12\x12.broker.WorkParams\x1a\x16.google.protobuf.Empty\x124\n" +
	"\tGetParams\x12\x13.broker.WorkContext\x1a\x12.broker.WorkParams\x125\n" +
	"\bSetState\x12\x11.broker.WorkState\x1a\x16.google.protobuf.Empty\x120\n" +
	"\bGetState\x12\x11.broker.WorkState\x1a\x11.broker.WorkState\x12=\n" +
	"\x0eSetProgressBar\x12\x13.broker.ProgressBar\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x15SubscribeProgressBars\x12\x18.broker.SubscribeRequest\x1a\x13.broker.ProgressBar0\x01B\fZ\n" +
	"./brokerpbb\x06proto3"

var (
	file_proto_broker_proto_rawDescOnce sync.Once
	file_proto_broker_proto_rawDescData []byte
)

func file_proto_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)))
	})
	return file_proto_broker_proto_rawDescData
}

var file_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_broker_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: broker.SubscribeRequest
	(*Event)(nil),            // 1: broker.Event
	(*WorkContext)(nil),      // 2: broker.WorkContext
	(*WorkParams)(nil),       // 3: broker.WorkParams
	(*WorkState)(nil),        // 4: broker.WorkState
	(*ProgressBar)(nil),      // 5: broker.ProgressBar
	(*emptypb.Empty)(nil),    // 6: google.protobuf.Empty
}
var file_proto_broker_proto_depIdxs = []int32{
	1, // 0: broker.Broker.PushEvents:input_type -> broker.Event
	0, // 1: broker.Broker.Subscribe:input_type -> broker.SubscribeRequest
	3, // 2: broker.Broker.RegisterParams:input_type -> broker.WorkParams
	2, // 3: broker.Broker.GetParams:input_type -> broker.WorkContext
	4, // 4: broker.Broker.SetState:input_type -> broker.WorkState
	4, // 5: broker.Broker.GetState:input_type -> broker.WorkState
	5, // 6: broker.Broker.SetProgressBar:input_type -> broker.ProgressBar
	0, // 7: broker.Broker.SubscribeProgressBars:input_type -> broker.SubscribeRequest
	6, // 8: broker.Broker.PushEvents:output_type -> google.protobuf.Empty
	1, // 9: broker.Broker.Subscribe:output_type -> broker.Event
	6, // 10: broker.Broker.RegisterParams:output_type -> google.protobuf.Empty
	3, // 11: broker.Broker.GetParams:output_type -> broker.WorkParams
	6, // 12: broker.Broker.SetState:output_type -> google.protobuf.Empty
	4, // 13: broker.Broker.GetState:output_type -> broker.WorkState
	6, // 14: broker.Broker.SetProgressBar:output_type -> google.protobuf.Empty
	5, // 15: broker.Broker.SubscribeProgressBars:output_type -> broker.ProgressBar
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_broker_proto_init() }
func file_proto_broker_proto_init() {
	if File_proto_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_proto_depIdxs,
		MessageInfos:      file_proto_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_proto = out.File
	file_proto_broker_proto_goTypes = nil
	file_proto_broker_proto_depIdxs = nil
}
