// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/broker.proto

package brokerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Broker_PushEvents_FullMethodName            = "/broker.Broker/PushEvents"
	Broker_Subscribe_FullMethodName             = "/broker.Broker/Subscribe"
	Broker_RegisterParams_FullMethodName        = "/broker.Broker/RegisterParams"
	Broker_GetParams_FullMethodName             = "/broker.Broker/GetParams"
	Broker_SetState_FullMethodName              = "/broker.Broker/SetState"
	Broker_GetState_FullMethodName              = "/broker.Broker/GetState"
	Broker_SetProgressBar_FullMethodName        = "/broker.Broker/SetProgressBar"
	Broker_SubscribeProgressBars_FullMethodName = "/broker.Broker/SubscribeProgressBars"
)

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerClient interface {
	PushEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, emptypb.Empty], error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	RegisterParams(ctx context.Context, in *WorkParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetParams(ctx context.Context, in *WorkContext, opts ...grpc.CallOption) (*WorkParams, error)
	SetState(ctx context.Context, in *WorkState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetState(ctx context.Context, in *WorkState, opts ...grpc.CallOption) (*WorkState, error)
	SetProgressBar(ctx context.Context, in *ProgressBar, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SubscribeProgressBars(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressBar], error)
}

type brokerClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerClient(cc grpc.ClientConnInterface) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) PushEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Broker_ServiceDesc.Streams[0], Broker_PushEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Broker_PushEventsClient = grpc.ClientStreamingClient[Event, emptypb.Empty]

func (c *brokerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Broker_ServiceDesc.Streams[1], Broker_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Broker_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *brokerClient) RegisterParams(ctx context.Context, in *WorkParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Broker_RegisterParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetParams(ctx context.Context, in *WorkContext, opts ...grpc.CallOption) (*WorkParams, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkParams)
	err := c.cc.Invoke(ctx, Broker_GetParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) SetState(ctx context.Context, in *WorkState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Broker_SetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetState(ctx context.Context, in *WorkState, opts ...grpc.CallOption) (*WorkState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkState)
	err := c.cc.Invoke(ctx, Broker_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) SetProgressBar(ctx context.Context, in *ProgressBar, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Broker_SetProgressBar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) SubscribeProgressBars(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressBar], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Broker_ServiceDesc.Streams[2], Broker_SubscribeProgressBars_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ProgressBar]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Broker_SubscribeProgressBarsClient = grpc.ServerStreamingClient[ProgressBar]

// BrokerServer is the server API for Broker service.
// All implementations must embed UnimplementedBrokerServer
// for forward compatibility.
type BrokerServer interface {
	PushEvents(grpc.ClientStreamingServer[Event, emptypb.Empty]) error
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	RegisterParams(context.Context, *WorkParams) (*emptypb.Empty, error)
	GetParams(context.Context, *WorkContext) (*WorkParams, error)
	SetState(context.Context, *WorkState) (*emptypb.Empty, error)
	GetState(context.Context, *WorkState) (*WorkState, error)
	SetProgressBar(context.Context, *ProgressBar) (*emptypb.Empty, error)
	SubscribeProgressBars(*SubscribeRequest, grpc.ServerStreamingServer[ProgressBar]) error
	mustEmbedUnimplementedBrokerServer()
}

// UnimplementedBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServer struct{}

func (UnimplementedBrokerServer) PushEvents(grpc.ClientStreamingServer[Event, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method PushEvents not implemented")
}
func (UnimplementedBrokerServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBrokerServer) RegisterParams(context.Context, *WorkParams) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterParams not implemented")
}
func (UnimplementedBrokerServer) GetParams(context.Context, *WorkContext) (*WorkParams, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParams not implemented")
}
func (UnimplementedBrokerServer) SetState(context.Context, *WorkState) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedBrokerServer) GetState(context.Context, *WorkState) (*WorkState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedBrokerServer) SetProgressBar(context.Context, *ProgressBar) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProgressBar not implemented")
}
func (UnimplementedBrokerServer) SubscribeProgressBars(*SubscribeRequest, grpc.ServerStreamingServer[ProgressBar]) error {
	return status.Error(codes.Unimplemented, "method SubscribeProgressBars not implemented")
}
func (UnimplementedBrokerServer) mustEmbedUnimplementedBrokerServer() {}
func (UnimplementedBrokerServer) testEmbeddedByValue()                {}

// UnsafeBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServer will
// result in compilation errors.
type UnsafeBrokerServer interface {
	mustEmbedUnimplementedBrokerServer()
}

func RegisterBrokerServer(s grpc.ServiceRegistrar, srv BrokerServer) {
	// If the following call panics, it indicates UnimplementedBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Broker_ServiceDesc, srv)
}

func _Broker_PushEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrokerServer).PushEvents(&grpc.GenericServerStream[Event, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Broker_PushEventsServer = grpc.ClientStreamingServer[Event, emptypb.Empty]

func _Broker_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Broker_SubscribeServer = grpc.ServerStreamingServer[Event]

func _Broker_RegisterParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).RegisterParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_RegisterParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).RegisterParams(ctx, req.(*WorkParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GetParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetParams(ctx, req.(*WorkContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).SetState(ctx, req.(*WorkState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetState(ctx, req.(*WorkState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_SetProgressBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressBar)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).SetProgressBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Broker_SetProgressBar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).SetProgressBar(ctx, req.(*ProgressBar))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_SubscribeProgressBars_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).SubscribeProgressBars(m, &grpc.GenericServerStream[SubscribeRequest, ProgressBar]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Broker_SubscribeProgressBarsServer = grpc.ServerStreamingServer[ProgressBar]

// Broker_ServiceDesc is the grpc.ServiceDesc for Broker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterParams",
			Handler:    _Broker_RegisterParams_Handler,
		},
		{
			MethodName: "GetParams",
			Handler:    _Broker_GetParams_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _Broker_SetState_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Broker_GetState_Handler,
		},
		{
			MethodName: "SetProgressBar",
			Handler:    _Broker_SetProgressBar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushEvents",
			Handler:       _Broker_PushEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Broker_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeProgressBars",
			Handler:       _Broker_SubscribeProgressBars_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/broker.proto",
}
